name: Bug report
description: Create a bug report to help us improve Keploy
title: "[bug]: "
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this bug report.

      
- type: textarea
  attributes:
    label: Current behavior
    description: A concise description of what you're experiencing and what you expect
    placeholder: |
      When I do <X>, <Y> happens and I see the error message attached below:
      ```...```
      What I expect is <Z>
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Add steps to reproduce this behaviour, include console or network logs and screenshots
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: dropdown
  id: browser
  attributes:
      label: "Browser"
      description: "What browser are you using ?"
      options:
        - Google Chrome
        - Brave
        - Microsoft Edge
        - Mozilla Firefox
        - Safari
        - Opera
        - Other
  validations:
      required: true

- type: checkboxes
  id: no-duplicate-issues
  attributes:
      label: "Checklist"
      options:
        - label: "I checked and didn't find similar issue"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/keploy/website/blob/main/CONTRIBUTING.md)"
          required: true

        - label: "I am willing to work on this issue (blank for no)"
          required: false

- type: markdown
  attributes:
    value: |
      Please add the respective Label to the Issue